app/Entity/File.php
<?php

namespace Filehosting\Entity;

/**
 * Class File
 * @package Filehosting\Entity
 */
class File extends BaseEntity
{
    /**
     * The status of the file is "loading"
     */
    const STATUS_IS_LOADING = "loading";

    /**
     * The status of the file is "loaded"
     */
    const STATUS_IS_LOADED = "loaded";

    /**
     * @var $id
     */
    private $id;

    /**
     * @var $name
     */
    private $name;

    /**
     * @var $original_name
     */
    private $original_name;

    /**
     * @var $path
     */
    private $path;

    /**
     * @var $thumbnail_path
     */
    private $thumbnail_path;

    /**
     * @var $description
     */
    private $description;

    /**
     * @var $size
     */
    private $size;

    /**
     * @var $mime_type
     */
    private $mime_type;

    /**
     * @var $user_id
     */
    private $user_id;

    /**
     * @var $user_token
     */
    private $user_token;

    /**
     * @var $media_info
     */
    private $media_info;

    /**
     * @var $user_name
     */
    private $user_name;

    /**
     * @var $user_avatar
     */
    private $user_avatar;

    /**
     * @var $can_manage
     */
    private $can_manage;

    /**
     * @var $comments
     */
    private $comments;

    /**
     * Is image?
     *
     * @return bool
     */
    public function isImage(): bool
    {
        if ($this->getType() === 'image') {
            return true;
        }
        return false;
    }

    /**
     * Is audio?
     *
     * @return bool
     */
    public function isAudio(): bool
    {
        if ($this->getType() === 'audio') {
            return true;
        }
        return false;
    }

    /**
     * Is video?
     *
     * @return bool
     */
    public function isVideo(): bool
    {
        if ($this->getType() === 'video') {
            return true;
        }
        return false;
    }

    /**
     * Get file type
     *
     * @return string
     */
    public function getType(): string
    {
        return explode('/', $this->mime_type)[0];
    }

    /**
     * Get file format
     *
     * @return string
     */
    public function getFormat(): string
    {
        return explode('/', $this->mime_type)[1];
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getOriginalName()
    {
        return $this->original_name;
    }

    /**
     * @param string $original_name
     */
    public function setOriginalName(string $original_name): void
    {
        $this->original_name = $original_name;
    }

    /**
     * @return mixed
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @param string $path
     */
    public function setPath(string $path): void
    {
        $this->path = $path;
    }

    /**
     * @return mixed
     */
    public function getThumbnailPath()
    {
        return $this->thumbnail_path;
    }

    /**
     * @param string $thumbnail_path
     */
    public function setThumbnailPath(string $thumbnail_path): void
    {
        $this->thumbnail_path = $thumbnail_path;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * @param int $size
     */
    public function setSize(int $size): void
    {
        $this->size = $size;
    }

    /**
     * @return mixed
     */
    public function getMimeType()
    {
        return $this->mime_type;
    }

    /**
     * @param string $mime_type
     */
    public function setMimeType(string $mime_type): void
    {
        $this->mime_type = $mime_type;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param mixed $user_id
     */
    public function setUserId($user_id): void
    {
        $this->user_id = $user_id;
    }

    /**
     * @return mixed
     */
    public function getUserToken()
    {
        return $this->user_token;
    }

    /**
     * @param mixed $user_token
     */
    public function setUserToken($user_token): void
    {
        $this->user_token = $user_token;
    }

    /**
     * @return mixed
     */
    public function getMediaInfo()
    {
        return $this->media_info;
    }

    /**
     * @param mixed $media_info
     */
    public function setMediaInfo($media_info): void
    {
        $this->media_info = $media_info;
    }

    /**
     * @return mixed
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * @param string $user_name
     */
    public function setUserName(string $user_name): void
    {
        $this->user_name = $user_name;
    }

    /**
     * @return mixed
     */
    public function getUserAvatar()
    {
        return $this->user_avatar;
    }

    /**
     * @param string $user_avatar
     */
    public function setUserAvatar(string $user_avatar): void
    {
        $this->user_avatar = $user_avatar;
    }

    /**
     * @return mixed
     */
    public function getCanManage()
    {
        return $this->can_manage;
    }

    /**
     * @param bool $can_manage
     */
    public function setCanManage(bool $can_manage): void
    {
        $this->can_manage = $can_manage;
    }

    /**
     * @return mixed
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param array $comments
     */
    public function setComments(array $comments): void
    {
        $this->comments = $comments;
    }
}

templates/base.twig
<!doctype html>
<html lang="{% block lang %}{% endblock %}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    {% block pageStyleSheet %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
    {% block script %}
        <script src="/bootstrap/js/jquery.min.js"></script>
        <script src="/bootstrap/js/jquery-ui.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
    {% endblock %}
    {% block pageScript %}{% endblock %}
</body>
</html>

templates/block-file.twig
 <div id="file_{{ file.name }}" class="block file">
    <div class="file__header">
        <div class="file__avatar">
            {% if file.userAvatar == NULL %}
                <img src="/image/avatar_default.jpg" alt="">
            {% else %}
                <img src="{{ file.userAvatar }}" alt="">
            {% endif %}
        </div>
        <div class="file__header-info">
            <div class="file__user-name">
                {% if file.userName == NULL %}
                    <h5>Аноним</h5>
                {% else %}
                    <h5><a href="">{{ file.userName }}</a></h5>
                {% endif %}
            </div>
            <div class="file__date">
                <span>{{ file.date|date("Y-m-d H:i:s") }}</span>
            </div>
        </div>
        <div class="dropdown">
            <button type="button" class="file__three-dots dropdown-toggle" data-toggle="dropdown">
                <span class="sr-only">Additional features</span>
                <span class="dot dot-left"></span>
                <span class="dot dot-center"></span>
                <span class="dot dot-rigth"></span>
            </button>
            <ul class="dropdown-menu">
                {% if file.canManage == true %}
                <li>
                    {% if controller == 'file' %}
                        <a class="pointer" onclick="showUpdateFileData('{{ file.name }}')"><span class="glyphicon glyphicon-pencil"></span> Редактировать</a>
                    {% else %}
                        <a class="pointer" href="/file/{{ file.name }}?updateFileData={{ file.name }}"><span class="glyphicon glyphicon-pencil"></span> Редактировать</a>
                    {% endif %}
                </li>
                <li>
                    <a href="" onclick="removeFile(event, '{{ file.name }}')"><span class="glyphicon glyphicon-trash"></span> Удалить</a>
                </li>
                {% else %}
                <li>
                    <a href="" onclick="event.preventDefault(); alert('Ваша жалоба отправлена в /dev/null')"><span class="glyphicon glyphicon-exclamation-sign"></span> Пожаловаться</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="file__body">
        <div class="file__description">
            <p>{{ file.description }}</p>
        </div>
        <div class="file__preview">
            {% if controller == 'file' %}
                <a data-toggle="modal" href="#modal-image"><img src="{{ file.thumbnailPath }}" alt=""></a>
            {% else %}
                <a href="/file/{{ file.name }}"><img src="{{ file.thumbnailPath }}" alt=""></a>
            {% endif %}
        </div>
        <div class="file__info">
            <div class="file__block-info">
                <div class="file__block-info-name">
                    <h4>{{ file.originalName }}</h4>
                </div>
                <div class="file__block-info-size">
                    <span>{{ formatSize(file.size) }}</span>
                </div>
            </div>
            {% if file.mediaInfo != null %}
                <button class="btn btn-default btn-sm" onclick="showOrHideTableFileInfo('{{ file.name }}')">Информация о файле</button>
                <div class="file__table-info table-responsive" id="table-file-info_{{ file.name }}">
                    <table class="table table-bordered table-condensed">
                        <tbody>
                        {% for k, v in json_decode(file.mediaInfo) %}
                            <tr>
                                <td>{{ k }}</td>
                                <td>{{ v }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="file__footer">
        <ul>
            <li>
                <a class="btn btn-primary" href="/download/{{ file.name }}" onclick="increaseNumOfDownloads('{{ file.name }}')"><span class="glyphicon glyphicon-download-alt"></span> Скачать</a>
            </li>
            <li>
                <div>
                    <span class="glyphicon glyphicon-cloud-download"></span> Загрузок <span id="downloads-count-{{ file.name }}">{{ file.downloads }}</span>
                </div>
            </li>
            <li>
                <div>
                    <span class="glyphicon glyphicon-comment"></span> Комментариев <span id="comments-count-{{ file.name }}">{{ file.comments|length }}</span>
                </div>
            </li>
        </ul>
    </div>
    <div class="file__comments">
        <form action="/comment/{{ file.name }}" method="post" id="form-comments-{{ file.name }}">
            <div id="comments-{{ file.name }}">
                {% if controller == 'files' %}
                    {% set showAllComments = 'false' %}
                    {% for comment in file.comments %}
                        {% if loop.length > 3 and showAllComments != 'on' %}
                            {% set showAllComments = 'true' %}
                        {% endif %}
                        {% if showAllComments == 'true' %}
                            <a id="show-all-comments-{{ file.name }}" class="file__show-all-comments" href="" onclick="getAllComments(event, '{{ file.name }}')">Показать все коментарии</a>
                            {% set showAllComments = 'on' %}
                        {% endif %}
                        {% if loop.index <= 3 %}
                            {% include 'comment.twig' %}
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {% for comment in file.comments %}
                        {% include 'comment.twig' %}
                    {% endfor %}
                {% endif %}
            </div>
            <input type="hidden" class="csrfName" name="{{csrf.keys.name}}" value="{{csrf.name}}">
            <input type="hidden" class="csrfValue" name="{{csrf.keys.value}}" value="{{csrf.value}}">
            <span id="comment-error-{{ file.name }}" class="file__comment-error"></span>
            <div class="input-group">
                <label class="sr-only" for="comment-text-{{ file.name }}">Comment</label>
                <div id="reply-user-name-{{ file.name }}" class="file__reply-user-name input-group-addon"></div>
                <textarea class="form-control" name="comment-text" id="comment-text-{{ file.name }}" rows="1" placeholder="Написать комментарий"></textarea>
                <span class="input-group-btn">
                    <button id="comment-submit-{{ file.name }}" type="button" class="btn btn-default" onclick="submitComment(event, '{{ file.name }}')">Отправить</button>
                </span>
            </div>
        </form>
    </div>
</div>

templates/comment-template.twig
<!-- Comment template -->
<div id="comment-template" class="comment comment-template" data-parent-id="">
    <div id="comment-template__depth">
        <div class="comment__avatar">
            <img id="comment-template__user-avatar">
        </div>
        <div class="comment__user-name">
            <h4 id="comment-template__user-name"></h4>
        </div>
        <div class="comment__text">
            <p id="comment-template__text"></p>
        </div>
        <div class="comment__date">
            <span id="comment-template__date"></span>
        </div>
        <span id="comment-template__reply-btn" class="comment__reply btn-link">Ответить</span>
        <input type="radio" id="comment-template__reply-input" name="reply-comment-id" hidden>
    </div>
</div>

templates/comment.twig
<div id="comment-{{ comment.id }}" class="comment" data-parent-id="{{ comment.parentId }}">
    <div class="comment__depth-{{ comment.getDepth }}">
        <div class="comment__avatar">
            {% if comment.userAvatar is not null %}
                <img src="{{ comment.userAvatar }}" alt="">
            {% else %}
                <img src="/image/avatar_default.jpg" alt="">
            {% endif %}
        </div>
        <div class="comment__user-name">
            {% if comment.userName is not null %}
                <h4>{{ comment.userName }}</h4>
            {% else %}
                <h4>Аноним</h4>
            {% endif %}
        </div>
        <div class="comment__text">
            <p>{{ comment.text }}</p>
        </div>
        <div class="comment__date">
            <span>{{ comment.date }}</span>
        </div>
        <span class="comment__reply btn-link" onclick="replyComment('{{ file.name }}', '{{ comment.id }}', '{{ comment.userName }}')">Ответить</span>
        <input type="radio" id="comment-reply-{{ comment.id }}" name="reply-comment-id" value="{{ comment.id }}" hidden>
    </div>
</div>

templates/modal-image.twig
<div id="modal-image" class="modal fade modal-image">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                {% if controller == 'file' %}
                    <img src="{{ file.thumbnailPath }}" alt="" data-dismiss="modal" aria-hidden="true">
                {% else %}
                    <img src="" alt="" data-dismiss="modal" aria-hidden="true">
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/navbar.twig
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed pull-left" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar top-bar"></span>
                <span class="icon-bar middle-bar"></span>
                <span class="icon-bar bottom-bar"></span>
            </button>
            <a class="navbar-brand" href="/">FileHosting</a>
            <div class="block-search-mobile">
                <form action="/files" class="navbar-form">
                    <input type="search" name="query" class="form-control search-input" placeholder="Поиск" aria-label="Поиск">
                </form>
            </div>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-left">
                {% if controller == 'files' %}
                    <li class="active"><a href="/files">Файлы</a></li>
                {% else %}
                    <li class=""><a href="/files">Файлы</a></li>
                {% endif %}
            </ul>
            <div class="block-search-desktop col-lg-4 col-md-4 col-sm-4">
                <form action="/files" class="navbar-form navbar-center">
                    <input type="search" name="query" class="form-control search-input" placeholder="Поиск" aria-label="Поиск">
                </form>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user is null %}
                    <li><a href="/login">Войти</a></li>
                    <li><a href="/register">Зарегистрироваться</a></li>
                {% else %}
                    <form id="form-logout" action="/logout" method="post">
                        <input id="csrfName" type="hidden" name="{{csrf.keys.name}}" value="{{csrf.name}}">
                        <input id="csrfValue" type="hidden" name="{{csrf.keys.value}}" value="{{csrf.value}}">
                    </form>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <img src="/image/avatar_default.jpg" alt="">
                            {{ user.name }}<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li id="logout" onclick="logOut(event)"><a href="#"><span class="glyphicon glyphicon-log-out"></span> Выйти</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/updateFileData.twig
{% if controller == 'upload' %}
    <div id="update-file-data_" class="update-file-data block">
{% else %}
    <div id="update-file-data_{{ file.name }}" class="update-file-data block">
{% endif %}
    <div class="update-file-data__header">
        {% if controller == 'upload' %}
            <h3 id="file-name"></h3>
        {% else %}
            <h3 id="file-name">{{ file.originalName }}</h3>
        {% endif %}
    </div>
    {% if controller == 'upload' %}
        <form action="/" method="post" id="form-update-data">
    {% else %}
        <form action="/update/{{ file.name }}" method="post" id="form-update-data">
    {% endif %}
        <div class="update-file-data__body">
            <div class="row">
                <input id="csrfName" type="hidden" name="{{csrf.keys.name}}" value="{{csrf.name}}">
                <input id="csrfValue" type="hidden" name="{{csrf.keys.value}}" value="{{csrf.value}}">
                <div class="form-group update-file-data__description">
                    <div class="col-lg-3">
                        <label class="control-label" for="description">Описание</label>
                    </div>
                    <div class="col-lg-9">
                        {% if controller == 'upload' %}
                            <textarea class="form-control description" name="description" id="description" rows="3" maxlength="120"></textarea>
                        {% else %}
                            <textarea class="form-control description" name="description" id="description" rows="3" maxlength="120">{{ file.description }}</textarea>
                        {% endif %}
                        <span id="description-error-text" class="text-danger"></span>
                        <p>
                            <span id="char-count"></span>
                            <span> / 120 знаков</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="update-file-data__footer">
            <div class="row">
                <div class="col-lg-6">
                    {% if controller == 'upload' %}
                        <a id="update-file-data-cancel" class="btn btn-default"> Отмена</a>
                    {% else %}
                        <a id="update-file-data-cancel" class="btn btn-default" href="/file/{{ file.name }}"> Отмена</a>
                    {% endif %}
                </div>
                <div class="col-lg-6 text-right">
                    <button id="update-file-data-submit" class="btn btn-primary" type="submit" name="formEditFile"> Сохранить</button>
                </div>
            </div>
        </div>
    </form>
</div>